# @package preprocessing.tabular

categorical_cols:
  - brand_name
  - CommercialTypeName4
  
numerical_cols:
  - seller_avg_price
  - seller_avg_item_time_alive
  - seller_median_price
  - PriceDiscounted
  - seller_total_items
  - seller_variety_mean
  - seller_avg_rating_5_share
  - ItemVarietyCount
  - item_time_alive
  - seller_total_order_accepted_30
  - desc_len
  - name_len
  - gmv_per_day
  - seller_total_gmv_30
  - desc_word_count
  - ItemAvailableCount
  - seller_available_mean
  - fraud_title_title_description_mismatch
  - fraud_desc_title_description_mismatch
  - seller_total_exemplar_accepted_30
  - seller_time_alive_y
  - seller_time_alive_x
  - seller_total_exemplar_returned_30
  - seller_total_gmv_90
  - seller_total_sales
  - seller_sum_rating_5
  - seller_total_exemplar_returned_value_30
  - GmvTotal90
  - ExemplarReturnedValueTotal90
  - seller_total_fake_returns_90
  - GmvTotal30
  - seller_total_photos
  - ExemplarReturnedCountTotal90
  - seller_sum_rating_1
  - seller_avg_return_rate
  - fraud_title_short_description
  - seller_sum_rating_4
  - OrderAcceptedCountTotal90
  - rating_5_count
  - ExemplarAcceptedCountTotal90
  - seller_total_videos
  - seller_sum_rating_3
  - fraud_desc_suspicious_numbers
  - ExemplarReturnedValueTotal7
  - seller_sum_rating_2
  - ExemplarAcceptedCountTotal30
  - OrderAcceptedCountTotal30
  - seller_total_fake_returns_30

scaling: "standard"