# @package preprocessing.text

# rules
max_length: 1024
apply_cleaning: true
apply_lemmatization: false
add_fraud_indicators: true

# NLTK setup
# Default NLTK data directory can be overridden with env var NLTK_DATA or CLI
nltk_data_dir: ${oc.env:NLTK_DATA,${hydra:runtime.cwd}/nltk_data}