# @package preprocessing.text

# rules
max_length: 512
apply_cleaning: true
apply_lemmatization: true
add_fraud_indicators: false

# NLTK setup
# Default NLTK data directory can be overridden with env var NLTK_DATA or CLI
nltk_data_dir: ${oc.env:NLTK_DATA,${hydra:runtime.cwd}/nltk_data}