epochs: 100
batch_size: 64

criterion:
  _target_: "torch.nn.BCEWithLogitsLoss"
  pos_weight: 15

optimizer:
  _target_: "torch.optim.Adam"
  lr: 1e-4
  weight_decay: 1e-5
  betas: [0.9, 0.999]

scheduler:
  _target_: "torch.optim.lr_scheduler.ReduceLROnPlateau"
  mode: "max"
  factor: 0.5
  patience: 3

#early_stopping:
#  patience: 10
#  monitor: "val_f1"
#  mode: "max"
  
validation:
  # frequency: 1
  threshold: 0.5