defaults:
  - preprocessing@preprocessing.text: text
  - preprocessing@preprocessing.image: image
  - preprocessing@preprocessing.tabular: tabular
  - model: architecture
  - training: default
  - experiment: default
  - calibration: default
  - _self_

project:
  name: fraud-detection
  seed: 42
  output_dir: ${hydra:runtime.output_dir}

# Data preparation settings
data_preparation:
  train_path: data/ml_ozon_train.csv
  test_path: data/test_full.csv
  output_dir: data

processors:
  tabular_processor_path: "data/tabular_processor.pkl"

inference:
  model_path: "${calibration.output_dir}/temperature_scaled_model.pt"
  output_path: "data/submission.csv"
  threshold: 0.5
  pr_curve_path: "data/pr_curve.png"

threshold:
  optimal_threshold_path: "data/optimal_threshold.json"