model:
  text:
    enabled: true
    name: "cointegrated/rubert-tiny2"
    pretrained: true
    projection_dim: 256
    dropout: 0.3
    
  image:
    enabled: false
    name: "efficientnet_b0"
    pretrained: true
    projection_dim: 256
    dropout: 0.3
    
  tabular:
    enabled: true
    # FTTransformer hyperparameters
    categories: []         # to be filled at runtime from TabularProcessor.fit()
    num_continuous: 0      # to be filled at runtime from TabularProcessor.fit()
    dim: 32
    projection_dim: 128    # FTTransformer dim_out
    depth: 6
    heads: 8
    attn_dropout: 0.1
    ff_dropout: 0.1
    
  classifier:
    hidden_dim: 512
    dropout: 0.5
    
  # Modality dropout for training robustness
  modality_dropout: 0.1  # Dropout rate for train (0.0 = no dropout)
  cache_dir: "cache"

fusion:
  _target_: "models.fusion.fusion.Fusion"
  type: "early"  # [early, late, gated]
    
  output_dim: 256
  dropout: 0.3
  
#  gating:
#    enabled: false
#    hidden_dim: 128