model:
  text:
    enabled: true
    name: "bert-base-uncased"
    pretrained: true
    projection_dim: 256
    dropout: 0.3
    
  image:
    enabled: true
    name: "resnet50"
    pretrained: true
    pool_type: learned
    projection_dim: 256
    dropout: 0.3
    
  tabular:
    enabled: true
    input_dim: 128
    hidden_dim: 256
    projection_dim: 256
    dropout: 0.3
    
  classifier:
    hidden_dim: 512
    dropout: 0.5
    
  # Modality dropout for training robustness
  modality_dropout: 0.0  # Dropout rate for train (0.0 = no dropout)