fusion:
  _target_: "models.fusion.fusion.Fusion"
  type: "early"  # [early, late, gated]
  
  input_dims:
    text: ${model.text.projection_dim}
    image: ${model.image.projection_dim}
    tabular: ${model.tabular.projection_dim}
    
  output_dim: 768
  dropout: 0.3
  
  gating:
    enabled: false
    hidden_dim: 128